#! /bin/bash

set -x

export TAPPERFROMGIT

# prepare example files
cd /tmp
tar xzf tapper-starterkit.tgz

# ===========================================================

# currently we rely Perl already built in baseimage
if false ; then
    /tmp/tapper-starterkit/utils/prepare-optperl
fi

# ===========================================================

# Perl libs
/tmp/tapper-starterkit/utils/prepare-perlmodule \
 Tapper::PRC \
 Tapper::Installer \
 Tapper::TestSuite::AutoTest \
 Tapper::TestSuite::HWTrack

# ==================== Python ====================

# currently we rely Python already built in baseimage
if false ; then
    /tmp/tapper-starterkit/utils/prepare-optpython
fi

# ==================== Python test suites ====================

PYTHONPREFIX=/opt/tapper/python

# Python libs
/tmp/tapper-starterkit/utils/prepare-pythonmodule \
 TestSuite-PyTAP \
 TestSuite-Metainfo \
 TestSuite-dom0-meta \
 TestSuite-Check-CPU-features \
 TestSuite-L3CID \
 TestSuite-AIM-Python \
 TestSuite-AutoTestWrapper-Python \
 TestSuite-CPUFreq-Python \
 TestSuite-CStates-Python \
 TestSuite-CTCS-Python \
 TestSuite-DIY-Python \
 TestSuite-HackBench-Python \
 TestSuite-HostCPUTest-Python \
 TestSuite-HTS-Python \
 TestSuite-KernBench-Python \
 TestSuite-KVM-Passthrough-Python \
 TestSuite-LLCBench-Python \
 TestSuite-LmBench-Python \
 TestSuite-LTP-Python \
 TestSuite-ParseLogs-Python \
 TestSuite-Phoronix-Python \
 TestSuite-RHV7-Python \
 TestSuite-SLBench-Python \
 TestSuite-StressAppTest-Python \
 TestSuite-SysBench-Python \
 TestSuite-TIOBench-Python \
 TestSuite-Topology-Python \
 TestSuite-TSMaster-Python

# ===========================================================

/tmp/tapper-starterkit/utils/create-symlinks
