#! /bin/bash

set -x

# config

PREFIX=/opt/tapper/python
PYTHONVERSION=2.6.6
PYTHONTGZ=Python-${PYTHONVERSION}.tgz
PYTHONURL=http://www.python.org/ftp/python/${PYTHONVERSION}/${PYTHONTGZ}
EASYINSTALL=setuptools-0.6c11
EASYINSTALLTGZ=${EASYINSTALL}.tar.gz
EASYINSTALLEGG=${EASYINSTALL}-py2.6.egg
EASYINSTALLURL=http://pypi.python.org/packages/source/s/setuptools/${EASYINSTALLTGZ}#md5=27a3fe3a4973c0cc97534bc9e9720c3d
#EASYINSTALLURL=http://pypi.python.org/packages/2.6/s/setuptools/${EASYINSTALLEGG}#md5=bfa92100bd772d5a213eedd356d64086

# Debian dependencies, maybe not strictly neccessary
#apt-get --yes --allow-unauthenticated install python-setuptools


# Python

cd /tmp
wget -nd -N $PYTHONURL
tar xzf $PYTHONTGZ
cd Python-$PYTHONVERSION
#make distclean
#./configure --prefix=${PREFIX}
#make -j6
##make test
#make install

# EasyInstall

cd /tmp
wget -nd -N $EASYINSTALLURL
tar xzf $EASYINSTALLTGZ
#sh $EASYINSTALLEGG --prefix=${PREFIX}
cd ${EASYINSTALL}
${PREFIX}/bin/python setup.py install
