#! /bin/bash

set -x

export TAPPERFROMGIT

# prepare example files
cd /tmp
tar xzf tapper-starterkit.tgz

# ===========================================================

# currently we rely Perl already built in baseimage
if false ; then
    /tmp/tapper-starterkit/utils/prepare-optperl
fi

# ===========================================================

/tmp/tapper-starterkit/utils/prepare-perlmodule \
 Tapper::PRC \
 Tapper::Installer \
 Tapper::TestSuite::AutoTest \
 Tapper::TestSuite::HWTrack

# ==================== Python ====================

/tmp/tapper-starterkit/utils/prepare-optpython

# ==================== Python test suites ====================

PYTHONPREFIX=/opt/tapper/python
for pkg in `find /pythonrepo/ -type f` ; do
    ${PYTHONPREFIX}/bin/easy_install $pkg
done

/tmp/tapper-starterkit/utils/create-symlinks
